inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-factory_bot

require:
  - rubocop-rspec_rails

AllCops:
  NewCops: enable

# Disable inline documentation since it is not practical or desired
# to add it to every class and module.
Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false