Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20250108052319_devise_create_users.rb'
    - 'db/migrate/20250114103232_create_active_storage_tables.active_storage.rb'
    - 'app/models/ability.rb'
    - 'app/controllers/carts_controller.rb'
    - 'app/controllers/categories_controller.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/20250114103232_create_active_storage_tables.active_storage.rb'
    - 'app/controllers/storehouses_controller.rb'
    - 'app/controllers/carts_controller.rb'
    - 'app/controllers/categories_controller.rb'
    - 'app/controllers/products_controller.rb'