# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

development:
  periodic_cleanup:
    class: CartsCleanupJob
    queue: background
    schedule: every 3 minutes
  periodic_cleanup:
    class: CleanExpiryPaymentCardJob
    queue: background
    schedule: every 2 hours

production:
  periodic_cleanup:
    class: CartsCleanupJob
    queue: background
    schedule: every day at midnight
  periodic_cleanup:
    class: CleanExpiryPaymentCardJob
    queue: background
    schedule: every 1 months
